import { Decoration } from "./decoration";
import { UpgradeWithTier } from "./upgrades";
import { Utility } from "./utilities";
import { Warp } from "./warp";

export enum RecipeElementNames {
  NEWBUCKS = "newbucks",
  PINK = "pink",
  COTTON = "cotton",
  TABBY = "tabby",
  ROCK = "rock",
  PHOSPHOR = "phosphor",
  PUDDLE = "puddle",
  BOOM = "boom",
  HUNTER = "hunter",
  CRYSTAL = "crystal",
  FIRE = "fire",
  BATTY = "batty",
  FLUTTER = "flutter",
  YOLKY = "yolky",
  GOLD = "gold",
  SABER = "saber",
  ANGLER = "angler",
  RINGTAIL = "ringtail",
  DERVISH = "dervish",
  TANGLE = "tangle",
  RADIANT = "radiant",
  HONEY = "honey",
  TWIN = "twin",
  SLOOMBER = "sloomber",
  HYPER = "hyper",
  SHADOW = "shadow",
  MAGMA = "magma",
  ROYAL = "royal",
  PRISMA = "prisma",
  BLACKINDIGO = "blackindigo",
  PETAL = "petal",
  AQUA = "aqua",
  DREAM = "dream",
  WAX = "wax",
  WILD_HONEY = "wildHoney",
  BRINE = "brine",
  JELLY = "jelly",
  SNOWFLAKE = "snowflake",
  SUNSAP = "sunsap",
  DRIFT = "drift",
  GLASS = "glass",
  MOTE = "mote",
  LAVA = "lava",
  PRIMORDY = "primordy",
  FOSSIL = "fossil",
  SAND = "sand",
  DIAMOND = "diamond",
  TANK_LINER = "tankLiner",
  STORAGE_CELL = "storageCell",
  STORAGE_UNIT = "storageUnit",
  POWER_CHIP = "powerChip",
  DASH_BOOT_MODULE = "dashBootModule",
  JETPACK_DRIVE = "jetpackDrive",
  HEART_MODULE = "heartModule",
  GOLDEN_SURESHOT_MODULE = "goldenSureshotModule",
  SHADOW_SURESHOT_MODULE = "shadowSureshotModule",
  DRONE_KEY = "droneKey",
  REGEN_MODULE = "regenModule",
  INJECTOR_MODULE = "injectorModule",
  DRONE_MODULE = "droneModule",
}

export const recipeElements: {
  [key in RecipeElementNames]: [string, string, string | null];
} = {
  newbucks: ["Newbucks", "misc/buck", null],
  pink: ["Pink Plort", "plorts/pink", "slimes/pink"],
  cotton: ["Cotton Plort", "plorts/cotton", "slimes/cotton"],
  tabby: ["Tabby Plort", "plorts/tabby", "slimes/tabby"],
  rock: ["Rock Plort", "plorts/rock", "slimes/rock"],
  phosphor: ["Phosphor Plort", "plorts/phosphor", "slimes/phosphor"],
  puddle: ["Puddle Plort", "plorts/puddle", "slimes/puddle"],
  boom: ["Boom Plort", "plorts/boom", "slimes/boom"],
  hunter: ["Hunter Plort", "plorts/hunter", "slimes/hunter"],
  crystal: ["Crystal Plort", "plorts/crystal", "slimes/crystal"],
  fire: ["Fire Plort", "plorts/fire", "slimes/fire"],
  batty: ["Batty Plort", "plorts/batty", "slimes/batty"],
  flutter: ["Flutter Plort", "plorts/flutter", "slimes/flutter"],
  yolky: ["Yolky Plort", "plorts/yolky", "slimes/yolky"],
  gold: ["Gold Plort", "plorts/gold", "slimes/gold"],
  saber: ["Saber Plort", "plorts/saber", "slimes/saber"],
  angler: ["Angler Plort", "plorts/angler", "slimes/angler"],
  ringtail: ["Ringtail Plort", "plorts/ringtail", "slimes/ringtail"],
  dervish: ["Dervish Plort", "plorts/dervish", "slimes/dervish"],
  tangle: ["Tangle Plort", "plorts/tangle", "slimes/tangle"],
  radiant: ["Radiant Ore", "resources/radiant", "items/resources/radiant"],
  honey: ["Honey Plort", "plorts/honey", "slimes/honey"],
  twin: ["Twin Plort", "plorts/twin", "slimes/twin"],
  sloomber: ["Sloomber Plort", "plorts/sloomber", "slimes/sloomber"],
  hyper: ["Hyper Plort", "plorts/hyper", "slimes/hyper"],
  shadow: ["Shadow Plort", "plorts/shadow", "slimes/shadow"],
  magma: ["Magma Honeycomb", "resources/magma", "resources/magma"],
  royal: ["Royal Jelly", "resources/royal", "resources/royal"],
  prisma: ["Prisma Plort", "resources/prisma", "items/resources/prisma"],
  blackindigo: ["Black Indigonium", "resources/blackindigo", "items/resources/blackindigo"],
  petal: ["Tin Petal", "resources/petal", "resources/petal"],
  aqua: ["Aqua Glass", "resources/aqua", "resources/aqua"],
  dream: ["Dream Bubble", "resources/dream", "resources/dream"],
  wax: ["Buzz Wax", "resources/wax", "resources/wax"],
  wildHoney: ["Wild Honey", "resources/wildhoney", "items/resources/wildhoney"],
  brine: ["Deep Brine", "resources/brine", "resources/brine"],
  jelly: ["Jellystone", "resources/jelly", "resources/jelly"],
  snowflake: ["Perfect Snowflake", "resources/snowflake", "items/resources/snowflake"],
  sunsap: ["Sun Sap", "resources/sunsap", "resources/sunsap"],
  drift: ["Drift Crystal", "resources/drift", "resources/drift"],
  glass: ["Storm Glass", "resources/glass", "resources/glass"],
  mote: ["Lightning Mote", "resources/mote", "resources/mote"],
  lava: ["Lava Dust", "resources/lava", "resources/lava"],
  primordy: ["Primordy Oil", "resources/primordy", "resources/primordy"],
  fossil: ["Slime Fossil", "resources/fossil", "resources/fossil"],
  sand: ["Silky Sand", "resources/sand", "resources/sand"],
  diamond: ["Strange Diamond", "resources/diamond", "resources/diamond"],
  tankLiner: ["Tank Liner", "upgrades/tankLiner", "upgrades/tankLiner"],
  storageCell: ["Storage Cell", "upgrades/storageCell", null],
  storageUnit: ["Storage Unit", "upgrades/storageUnit", null],
  powerChip: ["Power Chip", "upgrades/powerChip", null],
  dashBootModule: ["Dash Boot Module", "upgrades/dashBootModule", null],
  jetpackDrive: ["Jetpack Drive", "upgrades/jetpackDrive", null],
  heartModule: ["Heart Module", "upgrades/heartModule", null],
  goldenSureshotModule: ["Golden Sureshot Module", "upgrades/goldenSureshotModule", null],
  shadowSureshotModule: ["Shadow Sureshot Module", "upgrades/shadowSureshotModule", null],
  droneKey: ["Drone Key", "upgrades/droneKey", null],
  regenModule: ["Regenerator Module", "upgrades/regenModule", null],
  injectorModule: ["Injector Module", "upgrades/injectorModule", null],
  droneModule: ["Drone Station Module", "upgrades/droneModule", null],
};

export type Recipe = { [key in RecipeElementNames]?: number };

export enum UnlockRequirementNames {
  START = "start",
  POD = "pod",
  POLESTAR = "polestar",
  MOCHI = "mochi",
  VIKTOR = "viktor",
  OGDEN = "ogden",
  BOB = "bob",
  THORA = "thora",
  GIGI = "gigi",
  DOOR = "door",
  NIGHT = "night",
  GHOST = "ghost",
  IDK = "idk",
}

export const unlockRequirements: { [key in UnlockRequirementNames]: [string, string] } = {
  start: ["Available at the start", "misc/check"],
  pod: ["Unlocked via a Pod", "misc/pod"],
  polestar: ["Unlocked via Polestar Provisions", "misc/polestar"],
  mochi: ["Given by Mochi Miles", "ranchers/mochi"],
  viktor: ["Given by Viktor Humphries", "ranchers/viktor"],
  ogden: ["Given by Ogden Ortiz", "ranchers/ogden"],
  bob: ["Given by BOb", "ranchers/bob"],
  thora: ["Given by Thora West", "ranchers/thora"],
  gigi: ["Given by Gigi", "ranchers/gigi"],
  door: ["Found inside Shadow Vaults", "misc/door"],
  night: ["Unlocked via Night Market", "misc/nightmarket"],
  ghost: ["Found with roaming Ghost Drones", "misc/question"],
  idk: ["IDK yet", "misc/question"],
};

export function getEnumValue<T extends object>(
  enumObject: T,
  element: string | undefined,
): T[keyof T] | null {
  if (!element) {
    return null;
  }
  return Object.values(enumObject).find((value) => value === element) ?? null;
}

export const themeList: { [key: string]: [string, string] } = {
  any: ["Any", "misc/decorations"],
  fields: ["Rainbow Fields", "world/fields"],
  valley: ["Ember Valley", "world/valley"],
  strand: ["Starlight Strand", "world/strand"],
  bluffs: ["Powderfall Bluffs", "world/bluffs"],
  labyrinth: ["Grey Labyrinth", "world/labyrinth"],
  conservatory: ["The Conservatory", "world/conservatory"],
  golden: ["Golden Statues", "plorts/gold"],
  beach: ["Beach", "world/tidepools"],
  fun: ["Fun", "food/ranchersnslimes"],
};

export type BlueprintItem = UpgradeWithTier | Utility | Warp | Decoration;
