name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@8743aa11bfbda97acb45c151ae7a2e0b203f1914
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            cd /home/${{ secrets.SSH_USER }}/slimepedia2

            git fetch origin
            git reset --hard origin/main
            git clean -fd

            source ~/.nvm/nvm.sh
            nvm use

            npm ci
            npm run build